# Generated by Django 4.2.5 on 2023-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100, null=True)),
                ('Modelo', models.CharField(max_length=100, null=True)),
                ('anio', models.DateField(null=True)),
            ],
        ),
    ]
